---
- name: dalivery Zabbix agent file
  template:
     src: zabbix_agentd.j2
     dest: /etc/zabbix/zabbix_agentd.conf
     owner: root
     group: root
     mode: 0644
  notify: 
        - restart zabbix-agent