---
- name: delavery package
  copy:
    src: "zabbix-agent-4.0.2-1.el7.x86_64.rpm"
    dest: "/srv/zabbix-agent-4.0.2-1.el7.x86_64.rpm"
    owner: root
    group: root
    mode: 0666
  when: ansible_os_family == "RedHat"

- name: install package
  yum:
    name: "/srv/zabbix-agent-4.0.2-1.el7.x86_64.rpm"
    state:  present
  
