---
# tasks file for zabbix-agent
- name: include variables
  import_tasks: variables.yml

- name: include tasks config-repo
  import_tasks: config-repo.yml

- name: include tasks install-zabbix
  import_tasks: install-zabbix.yml

- name: include tasks configure-zabbix
  import_tasks: service-agent.yml 

- name: include tasks configure-zabbix
  import_tasks: configure-zabbix.yml
  